### PR TITLE
Deck mutations

### PR DESCRIPTION
**Pull request by ryancanton**
## Query/Mutation Effected
-query soundCard by deck_id
-mutation createDeck

## Describe Changes
allows FE to create a deck, and access sound_cards one at a time using a deck_id value

## Requested Reviewer(s)
Anyone

### CODE REVIEW

**Comment by this-is-joeking** [comment]
Mutation for creating a deck looks good along with the deck cards that get created, but we don't have a type for getting a single sound card

**Review by this-is-joeking — CHANGES_REQUESTED** [review]
Add query for individual sound_card

**Comment by this-is-joeking** [comment]
## Changes
Added query for getting sound card by deck_id which uses a model method to return the sound card and delete corresponding deck_card
Added sad path/edge cases for deck mutation and sound card query

**Review by sambcox — APPROVED** [review]
This all looks good!

**Pull request merged**
